apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      readinessProbe:
        httpGet:
          path: /api/v1/health
          port: 9555
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /api/v1/health
          port: 9555
        initialDelaySeconds: 15
        periodSeconds: 20
      terminationGracePeriodSeconds: 5
      containers:
      - name: ad-service
        image: ad-service
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: FRONTEND_URL
          value: "http://frontend.default.svc.cluster.local:3000"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
