apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      readinessProbe:
        httpGet:
          path: /api/v1/health
          port: 9555
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /api/v1/health
          port: 9555
        initialDelaySeconds: 15
        periodSeconds: 20
      terminationGracePeriodSeconds: 5
      containers:
      - name: recommendation-service
        image: recommendation-service
        ports:
        - containerPort: 9562
        env:
        - name: PORT
          value: "9562"
        - name: FRONTEND_URL
          value: "http://frontend.default.svc.cluster.local:3000"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "http://product-catalog-service.default.svc.cluster.local:9561/api/v1"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"