apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
  - port: 1025
    targetPort: 1025
    name: smtp
  - port: 8025
    targetPort: 8025
    name: web
  type: ClusterIP